version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "17:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.30
    - 14.14.31
    - 14.14.32
    - 14.14.33
    - 14.14.34
    - 14.14.35
    - 14.14.36
    - 14.14.41
  - dependency-name: typedoc-plugin-markdown
    versions:
    - 3.6.1
    - 3.7.1
  - dependency-name: eslint
    versions:
    - 7.24.0
  - dependency-name: "@types/node-fetch"
    versions:
    - 2.5.8
    - 2.5.9
  - dependency-name: typedoc
    versions:
    - 0.20.35
  - dependency-name: semantic-release
    versions:
    - 17.3.9
    - 17.4.0
    - 17.4.1
    - 17.4.2
  - dependency-name: "@types/jest"
    versions:
    - 26.0.20
    - 26.0.21
  - dependency-name: ts-jest
    versions:
    - 26.5.1
    - 26.5.2
    - 26.5.3
  - dependency-name: jsdoc-to-markdown
    versions:
    - 6.0.1
    - 7.0.0
